spring:
  application:
    name: taskmanagerproject

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

info:
  title: Task Manager API
  description: A simple task manager built with Spring Boot
  version: 1.0.0